/**
 * Generates supabase/seed.sql from the built-in demo dataset so the hosted
 * Supabase database starts with the same data the demo mode shows.
 *
 * Run: yarn seed:generate
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildDemoData } from "../src/lib/demo-data";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "..", "supabase", "seed.sql");

/** Deterministic UUID derived from the readable demo id. */
function uuid(id: string): string {
  const h = createHash("md5").update(`abia-dashboard:${id}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

function q(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
}

function insert(table: string, columns: string[], rows: string[][]): string {
  if (!rows.length) return "";
  const values = rows.map((r) => `  (${r.join(", ")})`).join(",\n");
  return `insert into ${table} (${columns.join(", ")}) values\n${values}\non conflict do nothing;\n\n`;
}

const d = buildDemoData();
let sql = `-- Generated by scripts/generate-seed.ts — do not edit by hand.\n-- Seeds the Abia State Dashboard database with the demo dataset.\n\n`;

sql += insert("sectors", ["id", "slug", "name", "description", "icon", "color", "sort_order"],
  d.sectors.map((s) => [q(uuid(s.id)), q(s.slug), q(s.name), q(s.description), q(s.icon), q(s.color), q(s.sort_order)]));

sql += insert("lgas", ["id", "name", "zone", "population"],
  d.lgas.map((l) => [q(uuid(l.id)), q(l.name), q(l.zone), q(l.population)]));

sql += insert("mdas", ["id", "sector_id", "name", "abbreviation", "description"],
  d.mdas.map((m) => [q(uuid(m.id)), q(uuid(m.sector_id)), q(m.name), q(m.abbreviation), q(m.description)]));

sql += insert("entities", ["id", "mda_id", "lga_id", "name", "entity_type"],
  d.entities.map((e) => [q(uuid(e.id)), q(uuid(e.mda_id)), q(uuid(e.lga_id)), q(e.name), q(e.entity_type)]));

sql += insert("thematic_areas", ["id", "sector_id", "name", "description", "frequency", "weight"],
  d.thematicAreas.map((t) => [q(uuid(t.id)), q(uuid(t.sector_id)), q(t.name), q(t.description), q(t.frequency), q(t.weight)]));

sql += insert("domains", ["id", "thematic_area_id", "name", "weight"],
  d.domains.map((x) => [q(uuid(x.id)), q(uuid(x.thematic_area_id)), q(x.name), q(x.weight)]));

sql += insert("indicators",
  ["id", "domain_id", "name", "unit", "direction", "target_value", "target_source", "weight"],
  d.indicators.map((i) => [
    q(uuid(i.id)), q(uuid(i.domain_id)), q(i.name), q(i.unit), q(i.direction),
    q(i.target_value), q(i.target_source), q(i.weight),
  ]));

sql += insert("time_periods", ["id", "frequency", "label", "start_date", "end_date"],
  d.timePeriods.map((p) => [q(uuid(p.id)), q(p.frequency), q(p.label), q(p.start_date), q(p.end_date)]));

// Results are chunked to keep individual statements a reasonable size
const resultCols = ["id", "indicator_id", "time_period_id", "entity_id", "abia_value", "nigeria_value", "target_value"];
for (let i = 0; i < d.results.length; i += 500) {
  sql += insert("results", resultCols,
    d.results.slice(i, i + 500).map((r) => [
      q(uuid(r.id)), q(uuid(r.indicator_id)), q(uuid(r.time_period_id)),
      r.entity_id ? q(uuid(r.entity_id)) : "null",
      q(r.abia_value), q(r.nigeria_value), q(r.target_value),
    ]));
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql);
console.log(
  `Wrote ${outPath}: ${d.sectors.length} sectors, ${d.mdas.length} MDAs, ${d.entities.length} entities, ` +
  `${d.indicators.length} indicators, ${d.timePeriods.length} periods, ${d.results.length} results`
);
